mach=[]
mach.append('bmw')
mach.append('ferrari')
mach.append('audi')
mach.append('mercedes')
mach.append('suzuki')
mach.append('subaru')
mach.append('cherry')
mach.append('chevrolet')
mach.append('ford')
mach.append('bugatti')
mach.insert(2, 'mazeratti')
del_ftr=mach.remove('bmw')
print(mach)
print(del_ftr)
